-- 0005_recovery_codes.up.sql

CREATE TABLE recovery_codes (
    user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- SHA-256, not bcrypt — a recovery code is a high-entropy random
    -- value generated by the engine, not a user-chosen secret, so
    -- there's no weak-guessing risk a slow hash would defend against.
    -- Globally unique on its own (random, high-entropy), so it's the
    -- primary key directly rather than introducing a separate id
    -- column just to have one.
    code_hash  TEXT PRIMARY KEY,
    used_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_recovery_codes_user_id ON recovery_codes(user_id);
