package admin

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/crydensync/cryden/v2/store"
)

// diagnosisHistoryLimit bounds how many recent audit events a
// diagnosis reads for one user. Generous compared to
// digestHighlightLimit because this report is about exactly one
// account rather than a whole system, so there is no volume problem
// to guard against — it exists only so a very old, very chatty
// account can't make one support ticket read the entire table.
const diagnosisHistoryLimit = 100

// UserByEmailReader is the read-only slice of store.UserStore a login
// diagnosis needs: look a user up, nothing else. No Create, no
// UpdatePasswordHash, no LockAccount — a diagnosis cannot unlock the
// very account it is reporting on, and that is enforced by this
// interface rather than promised in a comment.
type UserByEmailReader interface {
	GetByEmail(ctx context.Context, email string) (store.User, error)
}

// UserAuditHistoryReader is the read-only slice of store.AuditStore a
// login diagnosis needs beyond AuditReader: a single account's history,
// not a system-wide count. Distinct from AuditReader (which the weekly
// digest uses) because the two reports read the table two different
// ways — one across every user, one about a single one — and neither
// interface should grow a method the other doesn't need.
type UserAuditHistoryReader interface {
	ListByUser(ctx context.Context, userID string, limit int) ([]store.AuditEvent, error)
}

// UserSessionReader is the read-only slice of store.SessionStore a
// login diagnosis needs: whether the account has live sessions
// elsewhere. No Revoke, no RevokeAllForUser — a diagnosis reads
// whether someone is signed in, it never signs them out.
type UserSessionReader interface {
	ListByUser(ctx context.Context, userID string) ([]store.Session, error)
}

// loginFailureTypes are the audit event types a login diagnosis treats
// as evidence about *why* a sign-in didn't work, in the order they are
// checked. Everything else in the account's history (successful
// logins, password changes, and so on) is context, not a cause.
var loginFailureTypes = []store.AuditEventType{
	store.EventLoginFailed,
	store.EventAccountLocked,
	store.EventTOTPChallengeFailed,
	store.EventWebAuthnChallengeFailed,
	store.EventRecoveryCodeFailed,
	store.EventAnomalyDetected,
	store.EventCredentialStuffingDetected,
}

// LoginDiagnosis is the result of investigating one account's inability
// to sign in. Every field is read from a store; nothing here is
// generated by a model and nothing here can be un-derived from the
// account's own recorded history.
type LoginDiagnosis struct {
	Email string

	// Found is false when no account exists for Email at all — every
	// other field is zero-valued in that case. Deliberately not an
	// error: "no such account" is itself the diagnosis a support
	// ticket asked for, not a failure to produce one.
	Found bool

	Locked      bool
	LockedUntil time.Time

	FailedAttempts int

	// ActiveSessions is how many non-revoked sessions the account
	// currently holds. Zero alongside a recent EventLoginSuccess
	// usually means the user signed out (or was signed out) since,
	// not that login is broken.
	ActiveSessions int

	// RecentEvents is the account's own history, newest first, capped
	// at diagnosisHistoryLimit — enough for a human to read the whole
	// story of a bad week without shipping the account's entire
	// lifetime over the wire.
	RecentEvents []store.AuditEvent
}

// DiagnoseLogin investigates why one account might not be able to sign
// in and returns what its own recorded history shows — it never
// attempts a login, never clears a lockout, and never resets a
// counter. Every fact in the result already happened; this only reads
// it back and orders it for a human.
func DiagnoseLogin(ctx context.Context, users UserByEmailReader, audit UserAuditHistoryReader, sessions UserSessionReader, email string) (LoginDiagnosis, error) {
	d := LoginDiagnosis{Email: email}

	user, err := users.GetByEmail(ctx, email)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return d, nil
		}
		return LoginDiagnosis{}, fmt.Errorf("admin: looking up %s: %w", email, err)
	}
	d.Found = true
	d.FailedAttempts = user.FailedAttempts
	if user.LockedUntil != nil && user.LockedUntil.After(time.Now()) {
		d.Locked = true
		d.LockedUntil = user.LockedUntil.UTC()
	}

	sess, err := sessions.ListByUser(ctx, user.ID)
	if err != nil {
		return LoginDiagnosis{}, fmt.Errorf("admin: listing sessions for %s: %w", email, err)
	}
	d.ActiveSessions = len(sess)

	events, err := audit.ListByUser(ctx, user.ID, diagnosisHistoryLimit)
	if err != nil {
		return LoginDiagnosis{}, fmt.Errorf("admin: listing audit history for %s: %w", email, err)
	}
	d.RecentEvents = events

	return d, nil
}

// Text renders the diagnosis as something a support agent reads
// top-to-bottom: the account's current state first (the part most
// likely to be the actual answer), then the recent history that
// explains how it got there.
func (d LoginDiagnosis) Text() string {
	var b strings.Builder

	fmt.Fprintf(&b, "Login diagnosis for %s\n\n", d.Email)

	if !d.Found {
		b.WriteString("No account exists for this email address.\n")
		return b.String()
	}

	if d.Locked {
		fmt.Fprintf(&b, "Account is LOCKED until %s.\n", formatDetailTime(d.LockedUntil))
	} else {
		b.WriteString("Account is not locked.\n")
	}
	fmt.Fprintf(&b, "%s currently recorded (resets on the next successful sign-in).\n",
		pluralize(d.FailedAttempts, "consecutive failed attempt", "consecutive failed attempts"))
	fmt.Fprintf(&b, "%s currently active.\n", pluralize(d.ActiveSessions, "session is", "sessions are"))

	failures := d.recentFailureEvents()
	if len(failures) == 0 {
		b.WriteString("\nNo recent failure-type events in this account's history.\n")
	} else {
		fmt.Fprintf(&b, "\nRecent failure-type events (%s, newest first):\n",
			pluralize(len(failures), "event", "events"))
		for _, e := range failures {
			b.WriteString("  " + describeEvent(e) + " — " + string(e.Type) + "\n")
		}
	}

	if len(d.RecentEvents) > 0 {
		last := d.RecentEvents[0]
		fmt.Fprintf(&b, "\nMost recent event of any kind: %s (%s).\n", describeEvent(last), last.Type)
	}

	return b.String()
}

// recentFailureEvents filters RecentEvents down to loginFailureTypes,
// preserving the newest-first order ListByUser already returns them
// in. A separate pass rather than a second store query — the account's
// whole recent history was already read once, and this is the same
// data, viewed narrower.
func (d LoginDiagnosis) recentFailureEvents() []store.AuditEvent {
	wanted := make(map[store.AuditEventType]bool, len(loginFailureTypes))
	for _, t := range loginFailureTypes {
		wanted[t] = true
	}
	var out []store.AuditEvent
	for _, e := range d.RecentEvents {
		if wanted[e.Type] {
			out = append(out, e)
		}
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].CreatedAt.After(out[j].CreatedAt) })
	return out
}
