package memory

import (
	"context"
	"fmt"
	"sync"
	"time"

	"github.com/crydensync/cryden/internal/core"
)

// UserStore implements core.userStore using in-memory map
// Good for testing and development
type UserStore struct {
	mu      sync.RWMutex
	byEmail map[string]*core.User
	byID    map[string]*core.User
}

// NewUserStore creates new in-memory user
func NewUserStore() *UserStore {
	return &UserStore{
		byEmail: make(map[string]*core.User),
		byID:    make(map[string]*core.User),
	}
}

func (s *UserStore) Close() error {
	return nil
}

// Create stores a user
func (s *UserStore) Create(ctx context.Context, email, passwordHash string) (*core.User, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	//check if user already exits
	if _, exits := s.byEmail[email]; exits {
		return nil, core.ErrUserExists
	}

	// create user with generated byID
	user := &core.User{
		ID:           generateID(),
		Email:        email,
		PasswordHash: passwordHash,
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	}

	s.byEmail[email] = user
	s.byID[user.ID] = user

	return user, nil
}

// GetByEmail retrieves a user by email
func (s *UserStore) GetByEmail(ctx context.Context, email string) (*core.User, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	user, exits := s.byEmail[email]
	if !exits {
		return nil, core.ErrUserNotFound
	}
	return user, nil
}

// GetByID retrieve a user by ID
func (s *UserStore) GetByID(ctx context.Context, id string) (*core.User, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	user, exits := s.byID[id]
	if !exits {
		return nil, core.ErrUserNotFound
	}
	return user, nil
}

// UpdateEmail changes a user's email
func (s *UserStore) UpdateEmail(ctx context.Context, id, newEmail string) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	user, exits := s.byID[id]
	if !exits {
		return core.ErrUserNotFound
	}

	// Check of new email is taken
	if _, exits := s.byEmail[newEmail]; exits {
		return core.ErrUserExists
	}

	// Remove old email
	delete(s.byEmail, user.Email)

	// Upadte email
	user.Email = newEmail
	user.UpdatedAt = time.Now()

	// Add new email mapping
	s.byEmail[newEmail] = user

	return nil
}

// UpdatePassword changes user's password
func (s *UserStore) UpdatePassword(ctx context.Context, id, newPasswordHash string) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	user, exits := s.byID[id]
	if !exits {
		return core.ErrUserNotFound
	}

	user.PasswordHash = newPasswordHash
	user.UpdatedAt = time.Now()

	return nil
}

// Delete removes a user
func (s *UserStore) Delete(ctx context.Context, id string) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	user, exits := s.byID[id]
	if !exits {
		return core.ErrUserNotFound
	}

	delete(s.byEmail, user.Email)
	delete(s.byID, user.ID)

	return nil
}

// Helper functions to generate IDs
func generateID() string {
	return fmt.Sprintf("usr_%d", time.Now().UnixNano())
}
