-- 0005_recovery_codes.up.sql (SQLite)
--
-- Equivalent of Postgres migration 0005.

CREATE TABLE recovery_codes (
    user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- SHA-256, not bcrypt — a recovery code is a high-entropy random
    -- value generated by the engine, not a user-chosen secret, so
    -- there's no weak-guessing risk a slow hash would defend against.
    -- Globally unique on its own, so it's the primary key directly
    -- rather than introducing a separate id column just to have one.
    code_hash  TEXT PRIMARY KEY NOT NULL,
    used_at    TEXT,
    created_at TEXT NOT NULL
);

CREATE INDEX idx_recovery_codes_user_id ON recovery_codes(user_id);
